language: python
python:
  - '3.7'
install:
  - python -m pip install pipenv
  - pipenv install --dev --deploy

dist: bionic

services:
  - docker

script:
  - make test-ci
  - make test-e2e-ci

after_success:
  - make coverage-ci
